collections:
  works:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      previous_url: "/posts"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "post"
      previous_url: "/"
  - scope:
      path: ""
    values:
      layout: "default"